spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/demo_db
    password: postgres
    username: postgres

  flyway:
    url: jdbc:postgresql://localhost:5432/demo_db
    schemas: public
    user: postgres
    password: postgres
    baseline-on-migrate: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
